"""
Tests for singular_interface module.

Tests the Groebner Cover functionality using examples from the
Singular grobcov.lib documentation.

Author: Eli Weissler
"""

import pytest
import sympy as sym
from sympy import symbols, sympify


from sircuitenum.singular_interface import solve_with_singular, parse_singular_output, filter_redundant_branches
from sircuitenum.singular_interface import extract_mappings, flatten_branches


import json
def load_mathematica_benchmark(json_path):
    """
    Loads the JSON file generated by the Mathematica script and 
    converts it into the standard branch dictionary format.
    """
    with open(json_path, 'r') as f:
        raw_data = json.load(f)
        
    branches = []
    for i, item in enumerate(raw_data):
        # 1. Convert Mapping Strings -> SymPy
        mapping = {}
        for k, v in item['mapping'].items():
            key_sym = sym.sympify(k)
            val_sym = sym.sympify(v)
            mapping[key_sym] = val_sym
            
        # 2. Convert Constraints -> SymPy
        # Mathematica gives 'x != 0'. We convert to 'x' (meaning non-null)
        # or keep as strict inequality objects if your logic supports it.
        # Your filter uses 'nonnull' list (expressions that cannot be zero).
        nonnull = []
        for c in item['constraints']:
            # Parse "x != 0" string
            expr = sym.sympify(c)
            if isinstance(expr, sym.Ne): # strict inequality object
                # If expression is Ne(x, 0), extract x
                if expr.args[1] == 0:
                    nonnull.append(expr.args[0])
                else:
                    # Ne(x, y) -> x - y != 0
                    nonnull.append(expr.args[0] - expr.args[1])
            else:
                # Fallback for complex logic
                nonnull.append(expr)
        
        # 3. Create Branch Dict
        # Note: Mathematica Reduce gives exact solutions, so 'basis' is empty
        # (The basis is implicitly defined by the mappings).
        branches.append({
            'id': f"Math_{i+1}",
            'basis': [], 
            'mapping': mapping,
            'nonnull': nonnull,
            'params': [] # Mathematica resolves everything, usually no free params left unless implicit
        })
        
    return branches

def compare_results(my_branches, math_branches, verbose=True):
    """
    Verifies that every Mathematica solution is covered by (is a subset of)
    at least one of the user's branches.
    
    Args:
        my_branches (list): Output from your solver.
        math_branches (list): Loaded JSON from Mathematica.
        verbose (bool): Print details of matches/misses.
        
    Returns:
        (bool, list): Success status and list of uncovered Mathematica IDs.
    """
    
    # 1. Define the Subset Logic
    def is_subset(specific_branch, general_branch):
        # Setup Mapping
        if not specific_branch.get('mapping'): return False
        spec_map = specific_branch['mapping'].copy()
        
        # Augment specific map with basis vars (if any imply 0)
        for eq in specific_branch.get('basis', []):
            if isinstance(eq, sym.Symbol): spec_map[eq] = 0
                
        # CHECK 1: Do specific values satisfy General Basis?
        # (General Basis must evaluate to 0 given Specific Values)
        for eq in general_branch.get('basis', []):
            if eq.subs(spec_map).simplify() != 0: return False 

        # CHECK 2: Do specific values satisfy General Mapping?
        # (General Mapping equations LHS - RHS must be 0)
        if general_branch.get('mapping'):
            gen_map = general_branch['mapping']
            for lhs, rhs in gen_map.items():
                if (lhs - rhs).subs(spec_map).simplify() != 0:
                    return False

        # CHECK 3: Do specific values violate General Constraints (Holes)?
        # (If General says "Valid only if Z != 0", but Specific has Z=0, it's NOT a match)
        for constr in general_branch.get('nonnull', []):
            if constr == 1: continue
            if constr.subs(spec_map).simplify() == 0: return False
            
        return True

    # 2. Run the Comparison
    uncovered_ids = []
    
    print(f"Comparing {len(math_branches)} Mathematica branches against {len(my_branches)} User branches...\n")
    
    for math_b in math_branches:
        found_match = False
        matched_id = None
        
        for my_b in my_branches:
            # Check: Is Math (Specific) a subset of My (General)?
            if is_subset(math_b, my_b):
                found_match = True
                matched_id = my_b['id']
                break
        
        if found_match:
            if verbose:
                print(f"[OK] Math {math_b['id']}  -> Covered by User {matched_id}")
        else:
            if verbose:
                print(f"[FAIL] Math {math_b['id']} -> NOT FOUND in User results!")
                print(f"       Mapping: {math_b['mapping']}, Constraints: {math_b['nonnull']}")
            uncovered_ids.append(math_b['id'])

    # 3. Final Report
    success = len(uncovered_ids) == 0
    print("-" * 40)
    if success:
        print("SUCCESS: All Mathematica solutions are covered by your solver.")
    else:
        print(f"FAILURE: {len(uncovered_ids)} Mathematica solutions are missing from your output.")
        
    return success, uncovered_ids


class TestSingularParser():
   
    def test_parse(self):
        
        raw_output = """
        |||START||||||BRANCH|||1
        |||COMPONENT|||1
        |||PARAMS|||a,b
        |||VARS|||x,y
        |||CONSTRAINTS|||
        |||NUM_CONSTRAINT_SOLUTIONS|||-1
        |||NONNULL|||
        (a)
        |||BASIS|||
        (a2)*y+(-a3+b2)
        (a)*x+(-b)
        |||NUM_SOLUTIONS|||1
        |||BRANCH|||2
        |||COMPONENT|||1
        |||PARAMS|||a,b
        |||VARS|||x,y
        |||CONSTRAINTS|||
        (a)
        |||NUM_CONSTRAINT_SOLUTIONS|||1
        |||CONSTRAINT_BASIS|||
        a
        |||NONNULL|||
        (b),(a)
        |||BASIS|||
        1
        |||NUM_SOLUTIONS|||0
        |||BRANCH|||3
        |||COMPONENT|||1
        |||PARAMS|||a,b
        |||VARS|||x,y
        |||CONSTRAINTS|||
        (b)
        (a)
        |||NUM_CONSTRAINT_SOLUTIONS|||1
        |||CONSTRAINT_BASIS|||
        b
        a
        |||NONNULL|||
        1
        |||BASIS|||
        |||NUM_SOLUTIONS|||-1
        |||END|||
        """
        branches = parse_singular_output(raw_output, potential_vars=['x', 'y'], fixed_params=['a', 'b'])
        assert len(branches) == 2 # One branch has zero solutions
        assert branches[0]['vars'] == [sym.Symbol('x'), sym.Symbol('y')]
        assert branches[0]['num_solutions'] == 1
        assert branches[1]['constraints'] == [sym.Symbol('b'), sym.Symbol('a')]


    def test_parse_no_star(self):
        raw_output = """|||START||||||BRANCH|||1
        |||COMPONENT|||1
        |||PARAMS|||a,c
        |||VARS|||b
        |||CONSTRAINTS|||
        |||NUM_CONSTRAINT_SOLUTIONS|||-1
        |||NONNULL|||
        (a+1)
        |||BASIS|||
        (a+1)*b+(ac)
        |||NUM_SOLUTIONS|||1
        |||BRANCH|||2
        |||COMPONENT|||1
        |||PARAMS|||a,c
        |||VARS|||b
        |||CONSTRAINTS|||
        (a+1)
        |||NUM_CONSTRAINT_SOLUTIONS|||1
        |||CONSTRAINT_BASIS|||
        a+1
        |||NONNULL|||
        (c),(a+1)
        |||BASIS|||
        1
        |||NUM_SOLUTIONS|||0
        |||BRANCH|||3
        |||COMPONENT|||1
        |||PARAMS|||a,c
        |||VARS|||b
        |||CONSTRAINTS|||
        (c)
        (a+1)
        |||NUM_CONSTRAINT_SOLUTIONS|||1
        |||CONSTRAINT_BASIS|||
        c
        a+1
        |||NONNULL|||
        1
        |||BASIS|||
        |||NUM_SOLUTIONS|||-1
        |||END|||"""
        branches = parse_singular_output(raw_output, potential_vars=['b'], fixed_params=['a', 'c'])
        assert len(branches) == 2 # One branch has zero solutions
        assert sym.simplify(branches[0]['basis'][0] - ((symbols('a') + 1)*symbols('b') + symbols('a')*symbols('c'))) == 0

class TestSingularSolver():

    def setup_method(self):
        # Define commonly used symbols
        self.a, self.b = symbols('a b')  # Parameters
        self.x, self.y, self.z = symbols('x y z')  # Unknowns

    def test_01_parametric_singularity(self):
        """
        The "Divider" Test: ax = b
        Tests if the solver detects that 'a' cannot be zero without a special branch.
        """
        self.setup_method()
        print("\n--- Test 01: Parametric Singularity (ax = b) ---")
        eqs = [self.a * self.x - self.b]
        branches = solve_with_singular(eqs, [self.x])
        
        # Expectation: 
        # Branch 1: Generic (x = b/a)
        # Branch 2: Singular (a=0, b=0, x=Free)
        assert len(branches) == 2
        # "Should find at least 2 branches (Generic + Singular)"
        
        has_generic = False
        has_singular = False
        
        for b in branches:
            mappings = b['mapping']
            constraints = b['constraints']
            
            # Check for Generic Case
            if self.x in mappings and mappings[self.x] == self.b / self.a:
                has_generic = True
            
            # Check for Singular Case (Constraints contain a and b)
            # Note: exact constraint check can be tricky due to formatting, 
            # but usually it's [b, a] or similar.
            if constraints and self.a in mappings and self.b in mappings and self.x in b["free_vars"]:
                has_singular = True

        # Failed to find generic solution x = b/a
        assert has_generic
        # Failed to find singular case where x is Free
        assert has_singular

    def test_02_reducible_geometry(self):
        """
        The "Crossing" Test: x^2 - y^2 = 0
        Tests if facstd correctly splits the geometry into two linear branches.
        """
        self.setup_method()
        print("\n--- Test 02: Reducible Geometry (x^2 - y^2 = 0) ---")
        eqs = [self.x**2 - self.y**2]
        branches = solve_with_singular(eqs, [self.x, self.y])
        
        # Expectation:
        # Branch 1: x = y
        # Branch 2: x = -y (or vice versa)
        assert len(branches) == 2, "Should split x^2-y^2 into exactly 2 linear branches"
        
        solutions = [b['mapping'][self.x] for b in branches]
        assert self.y in solutions
        assert -self.y in solutions

    def test_03_inconsistent_system(self):
        """
        The "Impossible" Test: 1 = 0
        Tests if the solver correctly returns an empty list for no solutions.
        """
        print("\n--- Test 03: Inconsistent System (1 = 0) ---")
        self.setup_method()
        eqs = [sympify(1)] # 1 = 0
        branches = solve_with_singular(eqs, [self.x])
        
        assert len(branches) == 0, "Should return 0 branches for inconsistent system"

    def test_04_mixed_dimension(self):
        """
        The "Mixed Dim" Test: x(y-1) = 0
        Tests if it can return a Plane (dim 2) and a Line (dim 1) simultaneously.
        """
        print("\n--- Test 04: Mixed Dimension (x(y-1) = 0) ---")
        self.setup_method()
        eqs = [self.x * (self.y - 1)]
        branches = solve_with_singular(eqs, [self.x, self.y])
        
        # Expectation:
        # Case A: x = 0 (y is Free) -> Plane
        # Case B: y = 1 (x is Free) -> Plane/Line depending on z (here just x,y so lines)
        
        found_x_zero = False
        found_y_one = False
        
        for b in branches:
            m = b['mapping']
            if m.get(self.x) == 0: found_x_zero = True
            if m.get(self.y) == 1: found_y_one = True
            
        assert found_x_zero, "Failed to find branch x=0"
        assert found_y_one, "Failed to find branch y=1"

    def test_05_cyclic_3(self):
        """
        x + y + z = 0
        xy + yz + zx = 0
        xyz - 1 = 0
        """
        print("\n--- Test 05: Cyclic-3 Benchmark ---")
        self.setup_method()
        eqs = [
            self.x + self.y + self.z,
            self.x*self.y + self.y*self.z + self.z*self.x,
            self.x*self.y*self.z - 1
        ]
        # This system has exactly 6 discrete solutions (permutations of roots of unity)
        branches = solve_with_singular(eqs, [self.x, self.y, self.z])
        
        assert len(branches) == 6, "Cyclic-3 should have 6 solutions"
        unique_base = set()
        for b in branches:
            base = b["id"].split(".")[0]
            unique_base.add(base)
        assert len(unique_base) == 3
        
        # Check if the mappings are discrete (no free parameters)
        # Note: Cyclic-3 is 0-dimensional, so all vars should be mapped to numbers/algebraic values.
        for b in branches:
            assert b["free_vars"] == [], "Cyclic-3 solutions should have no free variables"
            assert b["vars"] == [self.x, self.y, self.z], "Cyclic-3 should have x,y,z as variables"


    def test_06_algebraic_number(self):
        """
        Tests if Singular returns the reduced algebraic form properly.
        """
        self.setup_method()
        print("\n--- Test 06: Algebraic Number (x^2 - 2 = 0) ---")
        eqs = [self.x**2 - 2]
        branches = solve_with_singular(eqs, [self.x])
        assert len(branches) == 2
        for b in branches:
            for var, val in b['mapping'].items():
                assert var == self.x
                assert val == sym.sqrt(2) or val == -sym.sqrt(2), "Algebraic number solution incorrect"


    def test_07_vs_mathematica_1(self):

        """
        
        """
        Z10, Z01, Z11, Z12, Z22, Z21, Z00, Z20, Z02 = sym.symbols('Z10 Z01 Z11 Z12 Z22 Z21 Z00 Z20 Z02')
        eq_set = [Z00*Z11 - 2*Z10*Z11 + Z10*Z21 + Z11*Z20 - 2*Z20*Z21,
                    Z00*Z22*(Z12 - Z22) + 2*Z12**2*Z20 - 2*Z12*Z20*Z22 + 2*Z20*Z22**2,
                    Z10*Z22*(Z12 - Z22) + Z12**2*Z20 - Z12*Z20*Z22 + 2*Z20*Z22**2,
                    Z11*(2*Z12 - Z22) - Z12*Z21 + 2*Z21*Z22]
        branches = solve_with_singular(eq_set)
        math_branches = load_mathematica_benchmark("test01.json")
        success, missing = compare_results(branches, math_branches, verbose=True)
        breakpoint()
        assert success, f"Missing Mathematica branches: {missing}"

class TestRedundantBranchFilter():

    def test_simple_subset_removal(self):
        """
        Test that a specific solution (all vars=0) is removed if it 
        is a subset of a general solution (Z20 free, others=0).
        """
        Z00, Z10, Z20, Z11, Z12, Z21, Z22 = symbols('Z00 Z10 Z20 Z11 Z12 Z21 Z22')
        # 1. The General Branch
        b_gen = {
            'id': 1,
            'basis': [Z11, Z12, Z21, Z22], 
            'mapping': {Z00: 0, Z10: 0}, 
            'nonnull': [1], 
            'params': [Z20] 
        }

        # 2. The Specific Branch
        b_spec = {
            'id': 2,
            'basis': [Z11, Z12, Z21, Z22, Z20, Z00, Z10],
            'mapping': {
                Z00: 0, Z10: 0, Z20: 0,   
                Z11: 0, Z12: 0, Z21: 0, Z22: 0
            },
            'nonnull': [1],
            'params': []
        }

        branches = [b_gen, b_spec]
        filtered = filter_redundant_branches(branches)

        ids = [b['id'] for b in filtered]

        assert 1 in ids
        assert 2 not in ids

    def test_keep_singularity_filling_branch(self):
        """
        Test that a subset is KEPT if it violates the 'nonnull' constraint 
        of the general branch. 
        (i.e., The general branch has a hole, and the specific branch fills it).
        """
        # 1. General Branch: Valid ONLY if Z22 != 0
        # Equation: Z12 = 5/Z22 (Hypothetically) -> Implies Z12*Z22 - 5 = 0
        # Let's use a simpler one: Z12 = Z22, but valid only if Z22 != 0
        Z00, Z10, Z20, Z11, Z12, Z21, Z22 = symbols('Z00 Z10 Z20 Z11 Z12 Z21 Z22')
        b_gen = {
            'id': 1,
            'basis': [Z12 - Z22],
            'mapping': [],
            'nonnull': [Z22], # CONSTRAINT: Z22 cannot be 0
            'params': [Z22]
        }

        # 2. Specific Branch: The Singularity (Z12=0, Z22=0)
        # This satisfies the equation (0 - 0 = 0), BUT...
        # It sets the constraint variable (Z22) to 0.
        b_spec = {
            'id': 2,
            'basis': [Z12, Z22],
            'mapping': {'Z12': 0, 'Z22': 0},
            'nonnull': [1],
            'params': []
        }

        branches = [b_gen, b_spec]
        filtered = filter_redundant_branches(branches)

        # Assertions
        ids = [b['id'] for b in filtered]
        assert 1 in ids
        assert 2 in ids, "The specific branch should be KEPT because it fills the Z22=0 hole."
        assert len(filtered) == 2

    def test_branch_26_consumes_branch_27(self):
        """
        Regression Test:
        Branch 26 (Decoupled Mode) allows Z00, Z10, Z20 to be free parameters, 
        provided all interaction terms (Z11, Z12, Z21, Z22) are zero.
        
        Branch 27 (Trivial Zero) has ALL variables (including energies) set to zero.
        
        B27 should be detected as a strict subset of B26.
        """
        Z00, Z10, Z20, Z11, Z12, Z21, Z22 = symbols('Z00 Z10 Z20 Z11 Z12 Z21 Z22')
        # Branch 26: The "Master" Decoupled Solution
        # Logic: Interactions are 0. Energies (Z00, Z10, Z20) are NOT in mapping/basis, so they are free.
        b26 = {
            'id': 26,
            'component': 2,
            # Implicitly: Z00, Z10, Z20 are free parameters
            'params': [Z00, Z10, Z20], 
            # Basis implies interactions are 0
            'basis': [Z22, Z21, Z12, Z11], 
            'mapping': {Z11: 0, Z12: 0, Z21: 0, Z22: 0}, 
            'nonnull': [1]
        }

        # Branch 27: The "Trivial" All-Zero Solution
        # Logic: Everything is 0.
        b27 = {
            'id': 27,
            'component': 3,
            'params': [], 
            # Basis implies everything is 0
            'basis': [Z00, Z10, Z20, Z11, Z12, Z21, Z22], 
            'mapping': {
                Z00: 0, Z10: 0, Z20: 0,
                Z11: 0, Z12: 0, Z21: 0, Z22: 0
            },
            'nonnull': [1]
        }

        branches = [b26, b27]
        filtered = filter_redundant_branches(branches)

        ids = [b['id'] for b in filtered]
        
        # B26 (General) should survive
        assert 26 in ids
        # B27 (Specific) should be removed
        assert 27 not in ids


def test_extract_mappings():
    """
    Test that mappings are extracted correctly and the real_only filter works.
    """
    # Create dummy branches with SymPy objects
    b1 = {
        'id': 1,
        'mappings': [
            {'x': 1, 'y': 2},          # Real
            {'x': sym.I, 'y': 2}       # Complex
        ]
    }
    b2 = {
        'id': 2,
        'mappings': [
            {'x': 5, 'y': 5}           # Real
        ]
    }
    
    branches = [b1, b2]

    # Case A: Extract All
    all_maps = extract_mappings(branches, real_only=False)
    assert len(all_maps) == 3
    assert {'x': 1, 'y': 2} in all_maps
    assert {'x': sym.I, 'y': 2} in all_maps

    # Case B: Real Only
    real_maps = extract_mappings(branches, real_only=True)
    assert len(real_maps) == 2
    assert {'x': 1, 'y': 2} in real_maps
    assert {'x': 5, 'y': 5} in real_maps
    # Ensure the complex one is gone
    assert {'x': sym.I, 'y': 2} not in real_maps


def test_flatten_branches():
    """
    Test that a branch with multiple mappings is exploded into 
    separate branches with unique IDs and singular 'mapping' keys.
    """
    # Branch 1 has 2 mappings (Needs flattening)
    b1 = {
        'id': 1,
        'some_data': 'A', # Ensure extra data is preserved
        'mappings': [
            {'val': 100}, 
            {'val': 200}
        ]
    }
    
    # Branch 2 has 0 mappings (Should be preserved as-is or handled gracefully)
    b2 = {
        'id': 2,
        'some_data': 'B',
        'mappings': [] 
    }

    branches = [b1, b2]
    flat = flatten_branches(branches)

    # Expect: 
    # b1 splits into "1.0" and "1.1"
    # b2 is passed through (or skipped depending on your logic, usually kept)
    
    # Check IDs
    ids = [b['id'] for b in flat]
    assert "1.0" in ids
    assert "1.1" in ids
    
    # Check Structure
    # Find the branch corresponding to the first mapping of b1
    b_flat_0 = next(b for b in flat if b['id'] == "1.0")
    
    # It should have 'mapping' (singular) matching the data
    assert b_flat_0['mapping'] == {'val': 100}
    # It should NOT have 'mappings' (plural)
    assert 'mappings' not in b_flat_0
    # It should retain other keys
    assert b_flat_0['some_data'] == 'A'


if __name__ == "__main__":
    # Run tests
    # test_solver = TestSingularParser()
    # test_solver.test_parse()
    # test_solver.test_parse_no_star()
    test_solver = TestSingularSolver()
    # test_solver.test_01_parametric_singularity()
    # test_solver.test_02_reducible_geometry()
    # test_solver.test_03_inconsistent_system()
    # test_solver.test_04_mixed_dimension()
    # test_solver.test_05_cyclic_3()
    # test_solver.test_06_algebraic_number()
    test_solver.test_07_vs_mathematica_1()
    # test_filter = TestRedundantBranchFilter()
    # test_filter.test_simple_subset_removal()
    # test_filter.test_keep_singularity_filling_branch()
    # test_filter.test_branch_26_consumes_branch_27()
    # test_extract_mappings()
    # test_flatten_branches()